[package]
name = "Composition"
version = "0.1.0"
authors = ["ElementG9 <garentyler@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.13"
colorful = "0.2.1"
lazy_static = "1.4.0"
ozelot = "0.9.0" # Ozelot 0.9.0 supports protocol version 578 (1.15.2)
toml = "0.5.6"
serde = { version = "1.0.114", features = ["serde_derive"]}
base64 = "0.12.3"
radix64 = "0.3.0"
mojang-api = "0.6.1"
log = "*"
fern = { version = "0.6", features = ["colored"] }
backtrace = "0.3.50"
